### ISSUE TITLE
Add support for relative script paths for `ahkpm include`

### ISSUE THREAD

**Issue by SaifAqqad** [joshuacc/ahkpm#174]
If I have a repo structure like this:
```
src/
├─ main.ahk

ahkpm.json

ahkpm-modules/
├─ github.com/
│  ├─ SaifAqqad/
│  │  ├─ VMR.ahk/
│  │  │  ├─ VMR.ahk

```

Running `ahkpm include gh:SaifAqqad/VMR.ahk -f .\src\main.ahk` would write `#Include, %A_ScriptDir%\ahkpm-modules\github.com\SaifAqqad\VMR.ahk\VMR.ahk` to the file, when it should write it relative to the path provided by the `-f` switch.
As in `#Include, %A_ScriptDir%\..\ahkpm-modules\github.com\SaifAqqad\VMR.ahk\VMR.ahk`

**Comment by joshuacc** [comment]
Thanks for the bug report! I should have a fix for this in the next day or two.

**Comment by joshuacc** [comment]
@SaifAqqad I've just merged the fix for this bug. I plan to publish ahkpm 0.7.0 in the next couple of days, but if you want to test the fix out before then, you can build from source.
