### ISSUE TITLE
`ahkpm include` generates `#Include` directives that are not compatible with AHK2

### ISSUE THREAD

**Issue by joshuacc** [joshuacc/ahkpm#180]
This was originally reported by @anonymous1184 in #176.

Quoted below:

---

Now, what about AHK v2? It was in alpha for like 10 years and in the past 3 quarters went from alpha to 15 betas to RC. Given that your project is written in Go, you can add compatibility regardless of what the users have installed. And is just the removal of the comma:

```ahk
#Include, %A_ScriptDir%\ahkpm-modules.ahk
;       ^------ v1 compatible only

#Include %A_ScriptDir%\ahkpm-modules.ahk
;       ^------ v1/v2 compatible

; Optionally
#Include %A_ScriptDir%\ahkpm-modules
```

**Comment by hwayne** [comment]
AND NOW ITS REAL
